# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcfc.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabStatus = QtWidgets.QTabWidget(self.centralwidget)
        self.tabStatus.setGeometry(QtCore.QRect(390, 310, 381, 281))
        self.tabStatus.setObjectName("tabStatus")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(90, 30, 31, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 70, 41, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(90, 70, 41, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(20, 110, 41, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(90, 110, 41, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(20, 150, 55, 16))
        self.label_20.setObjectName("label_20")
        self.ain0 = QtWidgets.QLabel(self.tab)
        self.ain0.setGeometry(QtCore.QRect(90, 150, 55, 16))
        self.ain0.setObjectName("ain0")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(20, 180, 47, 13))
        self.label_21.setObjectName("label_21")
        self.ain1 = QtWidgets.QLabel(self.tab)
        self.ain1.setGeometry(QtCore.QRect(90, 180, 47, 13))
        self.ain1.setObjectName("ain1")
        self.tabStatus.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setObjectName("pushButton")
        self.sol1Button = QtWidgets.QRadioButton(self.tab_2)
        self.sol1Button.setGeometry(QtCore.QRect(40, 70, 61, 17))
        self.sol1Button.setAutoExclusive(False)
        self.sol1Button.setObjectName("sol1Button")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(10, 120, 111, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(40, 10, 47, 13))
        self.label_27.setObjectName("label_27")
        self.valve1HorizontalSlider = QtWidgets.QSlider(self.frame)
        self.valve1HorizontalSlider.setGeometry(QtCore.QRect(40, 30, 41, 22))
        self.valve1HorizontalSlider.setStyleSheet("")
        self.valve1HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.valve1HorizontalSlider.setObjectName("valve1HorizontalSlider")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(90, 30, 21, 16))
        self.label_29.setObjectName("label_29")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.label_28.setObjectName("label_28")
        self.tabStatus.addTab(self.tab_2, "")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(390, 50, 381, 192))
        self.listView.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.listView.setObjectName("listView")
        self.pushStartStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushStartStop.setGeometry(QtCore.QRect(20, 80, 81, 31))
        self.pushStartStop.setCheckable(True)
        self.pushStartStop.setChecked(True)
        self.pushStartStop.setObjectName("pushStartStop")
        self.pushPause = QtWidgets.QPushButton(self.centralwidget)
        self.pushPause.setGeometry(QtCore.QRect(110, 80, 81, 31))
        self.pushPause.setObjectName("pushPause")
        self.fileEditBox = QtWidgets.QLineEdit(self.centralwidget)
        self.fileEditBox.setGeometry(QtCore.QRect(110, 130, 271, 22))
        self.fileEditBox.setObjectName("fileEditBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 130, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 91, 21))
        self.label_2.setObjectName("label_2")
        self.lastSampleNumber = QtWidgets.QLabel(self.centralwidget)
        self.lastSampleNumber.setGeometry(QtCore.QRect(120, 170, 21, 21))
        self.lastSampleNumber.setObjectName("lastSampleNumber")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 61, 21))
        self.label_4.setObjectName("label_4")
        self.CurrentSampleNumber = QtWidgets.QLabel(self.centralwidget)
        self.CurrentSampleNumber.setGeometry(QtCore.QRect(120, 200, 21, 21))
        self.CurrentSampleNumber.setObjectName("CurrentSampleNumber")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 170, 71, 21))
        self.label_3.setObjectName("label_3")
        self.sampleType = QtWidgets.QLabel(self.centralwidget)
        self.sampleType.setGeometry(QtCore.QRect(240, 170, 141, 21))
        self.sampleType.setObjectName("sampleType")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 200, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 200, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 121, 21))
        self.label_7.setObjectName("label_7")
        self.cryoSecCounter = QtWidgets.QLabel(self.centralwidget)
        self.cryoSecCounter.setGeometry(QtCore.QRect(150, 260, 31, 21))
        self.cryoSecCounter.setObjectName("cryoSecCounter")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(190, 260, 21, 21))
        self.label_9.setObjectName("label_9")
        self.cryoMinCounter = QtWidgets.QLabel(self.centralwidget)
        self.cryoMinCounter.setGeometry(QtCore.QRect(220, 260, 41, 21))
        self.cryoMinCounter.setObjectName("cryoMinCounter")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(280, 260, 41, 21))
        self.label_11.setObjectName("label_11")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 280, 111, 21))
        self.label_8.setObjectName("label_8")
        self.injectSecCounter = QtWidgets.QLabel(self.centralwidget)
        self.injectSecCounter.setGeometry(QtCore.QRect(150, 280, 31, 21))
        self.injectSecCounter.setObjectName("injectSecCounter")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(190, 280, 16, 21))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(220, 280, 31, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(280, 280, 31, 21))
        self.label_13.setObjectName("label_13")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(390, 20, 118, 22))
        self.timeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 310, 371, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.listWidget = QtWidgets.QListWidget(self.tab_3)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 361, 251))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.sequenceTable = QtWidgets.QTableWidget(self.tab_5)
        self.sequenceTable.setEnabled(True)
        self.sequenceTable.setGeometry(QtCore.QRect(0, 0, 361, 251))
        self.sequenceTable.setMinimumSize(QtCore.QSize(321, 0))
        self.sequenceTable.setAlternatingRowColors(True)
        self.sequenceTable.setObjectName("sequenceTable")
        self.sequenceTable.setColumnCount(3)
        self.sequenceTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sequenceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sequenceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sequenceTable.setHorizontalHeaderItem(2, item)
        self.sequenceTable.horizontalHeader().setDefaultSectionSize(115)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.idleCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.idleCheckBox.setGeometry(QtCore.QRect(30, 30, 70, 17))
        self.idleCheckBox.setChecked(True)
        self.idleCheckBox.setAutoExclusive(True)
        self.idleCheckBox.setTristate(False)
        self.idleCheckBox.setObjectName("idleCheckBox")
        self.normalCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.normalCheckBox.setGeometry(QtCore.QRect(110, 30, 70, 17))
        self.normalCheckBox.setAutoExclusive(True)
        self.normalCheckBox.setTristate(False)
        self.normalCheckBox.setObjectName("normalCheckBox")
        self.pfpCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.pfpCheckBox.setGeometry(QtCore.QRect(200, 30, 70, 17))
        self.pfpCheckBox.setAutoExclusive(True)
        self.pfpCheckBox.setTristate(False)
        self.pfpCheckBox.setObjectName("pfpCheckBox")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(680, 590, 75, 31))
        self.exitButton.setCheckable(False)
        self.exitButton.setAutoDefault(False)
        self.exitButton.setObjectName("exitButton")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 240, 81, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(150, 240, 31, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(190, 240, 16, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(220, 240, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(280, 240, 31, 16))
        self.label_26.setObjectName("label_26")
        self.tableChangeButton = QtWidgets.QPushButton(self.centralwidget)
        self.tableChangeButton.setGeometry(QtCore.QRect(20, 600, 75, 23))
        self.tableChangeButton.setObjectName("tableChangeButton")
        self.createTableButton = QtWidgets.QPushButton(self.centralwidget)
        self.createTableButton.setGeometry(QtCore.QRect(300, 600, 75, 23))
        self.createTableButton.setObjectName("createTableButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabStatus.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "From Stone Age to Somewhat Modern"))
        self.label_14.setText(_translate("MainWindow", "Pressure"))
        self.label_15.setText(_translate("MainWindow", "685"))
        self.label_16.setText(_translate("MainWindow", "Temp"))
        self.label_17.setText(_translate("MainWindow", "23"))
        self.label_18.setText(_translate("MainWindow", "Flow"))
        self.label_19.setText(_translate("MainWindow", "62.6"))
        self.label_20.setText(_translate("MainWindow", "Voltage"))
        self.ain0.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "Sol 1"))
        self.ain1.setText(_translate("MainWindow", "TextLabel"))
        self.tabStatus.setTabText(self.tabStatus.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.pushButton.setText(_translate("MainWindow", "Valve 1"))
        self.sol1Button.setText(_translate("MainWindow", "Valve 1"))
        self.label_27.setText(_translate("MainWindow", "Valve 1"))
        self.label_29.setText(_translate("MainWindow", "ON"))
        self.label_28.setText(_translate("MainWindow", "OFF"))
        self.tabStatus.setTabText(self.tabStatus.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.pushStartStop.setText(_translate("MainWindow", "START"))
        self.pushPause.setText(_translate("MainWindow", "PAUSE"))
        self.fileEditBox.setText(_translate("MainWindow", "c:\\rpt\\pressure\\bd092419"))
        self.label.setText(_translate("MainWindow", "File Name:"))
        self.label_2.setText(_translate("MainWindow", "Last Sample #:"))
        self.lastSampleNumber.setText(_translate("MainWindow", "56"))
        self.label_4.setText(_translate("MainWindow", "Sample #:"))
        self.CurrentSampleNumber.setText(_translate("MainWindow", "48"))
        self.label_3.setText(_translate("MainWindow", "Samp Type:"))
        self.sampleType.setText(_translate("MainWindow", "Cal"))
        self.label_5.setText(_translate("MainWindow", "SSV Pos.:"))
        self.label_6.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "Sec. from CRYO ON"))
        self.cryoSecCounter.setText(_translate("MainWindow", "540"))
        self.label_9.setText(_translate("MainWindow", "S"))
        self.cryoMinCounter.setText(_translate("MainWindow", "9"))
        self.label_11.setText(_translate("MainWindow", "Min"))
        self.label_8.setText(_translate("MainWindow", "Sec until INJECT"))
        self.injectSecCounter.setText(_translate("MainWindow", "1500"))
        self.label_10.setText(_translate("MainWindow", "S"))
        self.label_12.setText(_translate("MainWindow", "25"))
        self.label_13.setText(_translate("MainWindow", "Min"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "h:mm:ss"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "1 tank 13"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "2 tank 13"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "3 tank 13"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "4 tank 15"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "5 flask 13"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "6 flask 13"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "7 tank 0"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "8 flask 3"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "9 flask 3"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "10 tank 0"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "11 flask 5"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "12 flask 5"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "13 tank 0"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "14 flask 4"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "15 flask 4"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "16 tank 0"))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "17 that sure is a lot of typing"))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "18 should there be a couple of tabs with normal sequences?"))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "19 this is enough for now"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Custom"))
        item = self.sequenceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Samp Type"))
        item = self.sequenceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.sequenceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SSV Pos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Flasks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "PFP"))
        self.idleCheckBox.setText(_translate("MainWindow", "Idle"))
        self.normalCheckBox.setText(_translate("MainWindow", "Normal"))
        self.pfpCheckBox.setText(_translate("MainWindow", "PFP"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.label_22.setText(_translate("MainWindow", "Run Time"))
        self.label_23.setText(_translate("MainWindow", "0"))
        self.label_24.setText(_translate("MainWindow", "S"))
        self.label_25.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "Min"))
        self.tableChangeButton.setText(_translate("MainWindow", "Save Edits"))
        self.createTableButton.setText(_translate("MainWindow", "Create Table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

